spring:
  application:
    name: TickersSystem
  datasource:
    url: jdbc:postgresql://localhost:5437/tickets
    username: postgres
    password: sa
    driverClassName: org.postgresql.Driver


  flyway:
    enabled: true
    user: postgres
    password: sa
    schemas: public
    url: jdbc:postgresql://localhost:5437/tickets

data:
  names: src/main/resources/names.txt
  emails: src/main/resources/emails.txt
  phone_numbers: src/main/resources/phone_numbers.txt
  eventNames: src/main/resources/eventNames.txt
  places: src/main/resources/places.txt