spring:
  application:
    name: TickersSystem
  datasource:
    url: jdbc:postgresql://localhost:5437/tickets
    username: postgres
    password: sa
    driverClassName: org.postgresql.Driver


  flyway:
    enabled: true
    user: postgres
    password: sa
    schemas: public
    url: jdbc:postgresql://localhost:5437/tickets

data:
  places: src/main/resources/places.txt